# Generated by Django 3.0.4 on 2020-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonic',
            name='placeLatitude',
            field=models.IntegerField(default=234523, verbose_name='LatitudLugar'),
            preserve_default=False,
        ),
    ]
