# Generated by Django 3.0.4 on 2020-05-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic', '0004_auto_20200513_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasonic',
            name='placeLatitude',
            field=models.FloatField(verbose_name='LatitudLugar'),
        ),
        migrations.AlterField(
            model_name='ultrasonic',
            name='placeLength',
            field=models.FloatField(verbose_name='PlaceLength'),
        ),
    ]
